# -*- coding: utf-8 -*-
"""ggg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pFIxH63RZ-hgsoJ4tK3ey0zsi_tEPKS
"""

n = int(input())
score = [[0 for j in range(5)]for i in range(n)]
g = [[0 for j in range(5)]for i in range(n)]
grade = [[0 for j in range(5)]for i in range(n)]
all_kit = [2,2,3,3,3]
gpa = [0]*n
sum_point = 0
def point():
  for i in range(n):
    for j in range(5):
      if score[i][j] >=80 and score[i][j]<100:
        g[i][j] = 'A'
        grade[i][j] = 4
      elif score[i][j]< 80 and score[i][j]>= 75:
        g[i][j] = 'B+'
        grade[i][j] = 3.5
      elif score[i][j] <75 and score[i][j]>=70:
        g[i][j] = 'B'
        grade[i][j] = 3
      elif score[i][j] < 70 and score[i][j]>= 65:
        g[i][j] = 'C+'
        grade[i][j] = 2.5
      elif score[i][j] < 65 and score[i][j]>= 60:
        g[i][j] = 'C'
        grade[i][j] = 2
      elif score[i][j] < 60 and score[i][j]>= 55:
        g[i][j] = 'D+'
        grade[i][j] = 1.5
      elif score[i][j] < 55 and score[i][j]>= 50:
        g[i][j] = 'D'
        grade[i][j] = 1
      elif score[i][j] < 50 and score[i][j]>= 0:
        g[i][j] = 'F'
        grade[i][j] = 0 

 #input
for i in range(n):
  for j in range(5):
    score[i][j] = int(input())

for i in range(n):
  for j in range(5):
    sum_point += grade[i][j]*all_kit[i]
    gpa[i] = sum_point/13
point()

#score
print('Score')
for i in range(n):
  for j in range(5):
    print(score[i][j],end = ' ')
  print()

#grade
print('Grade')
for i in range(n):
  for j in range(5):
    print(g[i][j],end = ' ')
  print()

print('Studen : GPA')
for i in range(n):
  print(i+1,end = '  ')
  print(round(gpa[i],2))
  print()

