# -*- coding: utf-8 -*-
"""้his.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4A-pd4RXJNVd_O0fdZTV-AnIPG9L4yl
"""

his = {}
for i in range(0, 8):
    while True:
        x = int(input(""))
        if x >= 0 and x <= 255 :
            his[i] = x
            break
        else:
            print("Please you input try again")
            continue
print("***The Histrogram***")
for i in range(0, 8):
    for i in range(0, his[i]):
        print("=", end="")
    print("")