# -*- coding: utf-8 -*-
"""maxtrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dCDSUYaXBpF5IUvPPrz7Vf6M47Qx1cuw
"""

row= int(input())
column= int(input())
A=[[0 for j in range(column)]for i in range(row)]
B=[[0 for j in range(column)]for i in range(row)]
sum=[[0 for j in range(column)]for i in range(row)]
for i in range (row):
  for j in range (column):
    A[i][j]=int(input())
for i in range (row):
  for j in range (column):
    B[i][j]=int(input())
for i in range (row):
  for j in range (column):
    sum[i][j]=(B[i][j]-A[i][j])/2
print('Matrix X')
for i in range (row):
  print('|' , end=' ')
  for j in range (column):
    print(sum[i][j], end=' ')
  print('|')